# Generated by Django 4.2.10 on 2024-03-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
