# Generated by Django 4.2.10 on 2024-03-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_userprofile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=30),
        ),
    ]
