# Generated by Django 4.2.8 on 2024-04-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_worksheet_category_alter_worksheet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='category',
            field=models.CharField(choices=[('English', 'English'), ('Math', 'Math'), ('History', 'History'), ('Science', 'Science'), ('Physics', 'Physics'), ('Calculus', 'Calculus')], default='English', max_length=50),
        ),
    ]
