# Generated by Django 4.2.8 on 2024-04-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_comment_totaldownvotes_comment_totalupvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile_picture.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
